---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: eventstream
spec:
  ports:
  - port: 29092
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker
  namespace: eventstream
spec:
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.1.1
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
          #KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        ports:
        - containerPort: 9092
---
apiVersion: batch/v1
kind: Job
metadata:
  name: topics-quickstart
  namespace: eventstream
spec:
  template:
    metadata:
      name: topics-quickstart
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.1.1
        command: ["kafka-topics"]
        args: ["--create", "--topic", "PAGE_VISITS", "--partitions", "1", "--replication-factor", "1", "--if-not-exists", "--zookeeper", "zookeeper:32181"]
      restartPolicy: Never