apiVersion: batch/v1
kind: Job
metadata:
  name: topics-describe
  namespace: eventstream
spec:
  template:
    metadata:
      name: topics-describe
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.1.1
        command: ["kafka-topics"]
        args: ["--describe", "--topic", "my-topic", "--zookeeper", "zookeeper:32181"]
      restartPolicy: Never