---
apiVersion: v1
kind: Service
metadata:
  name: ksql-server
  namespace: eventstream
spec:
  ports:
  - port: 8088
  clusterIP: None
  selector:
    app: ksql-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ksql-server
  namespace: eventstream
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ksql-server
    spec:
      containers:
      - name: ksql-server
        image: confluentinc/cp-ksql-server:5.0.0-beta180702222458
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KSQL_OPTS
          value: "-Dlisteners=http://0.0.0.0:8088/ -Dksql.streams.replication.factor=1"
        ports:
        - containerPort: 8088
